root="."
tmp_dir="tmp"

[build]
cmd="go build -o ./tmp/main ."
bin="tmp/main"
full_bin="APP_ENV=dev APP_USER=air ./tmp/main 80"

include_ext=["go", "tpl", "tmpl", "html"]
exclude_dir=["assets", "tmp", "vender"]
include_dir=[""]
exclude_file=[]
exclude_regex=["_test.go"]
exclude_unchanged=true
follow_symlink=true
log="air.log"
delay=1000
step_on_error=true
send_inteeeupt=false
kill_delay=500

[log]
time=false

[color]
main="magenta"
watcher="cyan"
build="yellow"
runner="green"

[misc]
clean_on_exit=true