version: "3.9"

services:
  app:
    image: gotodo
    build:
      args:
        - target=dev
    environment:
      TODO_DB_HOST: todo-db
      TODO_DB_PORT: 3306
      TODO_DB_USER: todo
      TODO_DB_PASSWORD: todo
      TODO_DB_DATABASE: todo
      TODO_ENV: dev
      PORT: 8008
      TODO_REDIS_HOST: todo-redis
      TODO_REDIS_PORT: 6379
    volumes:
      - .:/app
    ports:
      - "18000:8008"

  todo-db:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: todo-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_DATABASE: todo
    volumes:
      - todo-db-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - 33306:3306

  todo-redis:
    image: "redis:latest"
    container_name: todo-redis
    ports:
      - "36379:6379"
    volumes:
      - todo-redis-data:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - ./redisinsight:/db
    depends_on:
      - todo-redis

volumes:
  todo-db-data:
  todo-redis-data: